/*
  resources.h
  Reaper Plugin

  Created by Daniel Lindenfelser on 24.06.14.
*/

#include "WDL/swell/swell.h"
#include "WDL/swell/swell-dlggen.h"

#define IDD_SOUNDBOARD 12345

#define IDC_SOUNDBOARD 2000

#ifndef SWELL_DLG_SCALE_AUTOGEN
#define SWELL_DLG_SCALE_AUTOGEN 1.7
#endif
#ifndef SWELL_DLG_FLAGS_AUTOGEN
#define SWELL_DLG_FLAGS_AUTOGEN SWELL_DLG_WS_FLIPPED|SWELL_DLG_WS_NOAUTOSIZE
#endif

#ifndef SET_IDD_SOUNDBOARD_SCALE
#define SET_IDD_SOUNDBOARD_SCALE SWELL_DLG_SCALE_AUTOGEN
#endif
#ifndef SET_IDD_SOUNDBOARD_STYLE
#define SET_IDD_SOUNDBOARD_STYLE SWELL_DLG_FLAGS_AUTOGEN|SWELL_DLG_WS_RESIZABLE
#endif
SWELL_DEFINE_DIALOG_RESOURCE_BEGIN(IDD_SOUNDBOARD,SET_IDD_SOUNDBOARD_STYLE,"Soundboard",210,48,SET_IDD_SOUNDBOARD_SCALE)
BEGIN

END
SWELL_DEFINE_DIALOG_RESOURCE_END(IDD_SOUNDBOARD)
